name: featureCI

on:
  push:
    branches:
      -'**'
jobs:
  first_job:
    runs_on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test feature CI
        run: |
            echo "Building and testing..."
          

