name: feature CI

on:
  push:
    branches:
      - '**'
    paths-ignore:
      - postman

jobs:
  first_job:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Build and Test feature CI
        run: |
            echo "Building and testing..."
          

